### PR TITLE
Strip ansi codes using regex

### LINKED ISSUE #48: Clean up stack traces
As mentioned in #47 the stack traces are polluted with `[22m` and other ANSI codes, likely related to bolding certain part of the text.  We need to figure out how to make jest only return plain-text, or strip these out after the fact.

### PR DESCRIPTION
**Pull request by msfeldstein**
Fixes #48 

Strips out ansi codes using a regex.  the `strip-ansi` library works on actual unicode strings, but this is just a regular utf8 encoded string with escaped unicode characters in it so a raw regex was needed.

Also removes the now-defunct loading message stuff from run-tests

### CODE REVIEW

File: server/jest-controller/run-test.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ module.exports = async (domain, test) => {
     );
     let jsonStr = "";
     jest.stdout.on("data", (data) => {
-      jsonStr += data.toString();
+      jsonStr += data.toString().replace(/\\u001b\[[0-9]{1,2}m/g, "");
```
Comment (JakeUrban) [inline server/jest-controller/run-test.js:16]: Do we not need string quotations around this regex?

**Review by JakeUrban — APPROVED** [review]
One question but looks good

File: server/jest-controller/run-test.js (hunk 1 above)
Comment (msfeldstein) [reply server/jest-controller/run-test.js:16]: In JS regexes are a first class concept.  You can parse it from a string. `const re = new RegExp('/whatev/g')` is equivalent to a raw `const re = /whatev/g`
