### PR TITLE
Fixed StaleElementRefereceError

### LINKED ISSUE #68: Fix StaleElementReferenceError bug
This error happens every-so-often during interactive tests. If one fails, the rest do, so this increases the urgency. I'm guessing this happens because we're not waiting long enough for the page to load? Will have to debug.
```
StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: headless chrome=80.0.3987.132)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
```

### PR DESCRIPTION
**Pull request by JakeUrban**
resolves #68

Turns out, we weren't using `await` on the `sendKeys` call, so it wouldn't get caught by the try/catch block. `forEach` doesn't work with async/await so I changed that as well. 

I also `clear()` the keys before trying to submit them. Sometimes we would fail to submit the first time, add the text to the keys again, and get an invalid email error.

### CODE REVIEW

File: cases/util/interactive.js [hunk 1]
```diff
@@ -67,11 +67,13 @@ export const doInteractiveFlow = async ({
   });
   const completePage = async () => {
     try {
+      let el;
       const elements = await driver.findElements(By.css("[test-value]"));
-      elements.forEach((el) => {
-        const val = el.getAttribute("test-value");
-        el.sendKeys(val);
-      });
+      for (el of elements) {
```
Comment (msfeldstein) [inline cases/util/interactive.js]: you can do `for (let el of elements) {` instead of hoisting the `let el` above

**Review by msfeldstein — APPROVED** [review]
oy good catch
